### ISSUE TITLE
% Lanaldia

### ISSUE THREAD

**Issue by rgonzalez2017** [PasaiakoUdala/egutegia#15]
%100 lanaldia 7 ordu eta 21 minutu dira baina hori 7,36 ordu dira (ez 7,21) 
Plantillan aldatu dut baina nonbait gehiago aldatu behar da?

**Comment by ikerib** [comment]
Txantiloian zehaztutakoa gero egutegira kopiatzen dira, beraz egutegi bakoitzean aldatu beharko zen.
