### ISSUE TITLE
oporren abisuak

### ISSUE THREAD

**Issue by rgonzalez2017** [PasaiakoUdala/egutegia#24]
Astelehenetan hurrengo 15 egunetako oporren laburpena...
Aurrerago teknikari bakoitzari bere saileko laburpena...

Ahal bada!

**Comment by ikerib** [comment]
working on it!


iKER

rgonzalez2017<notifications@github.com> igorleak hau idatzi zuen (2017(e)ko
maiatza 30 08:36):
